sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories: 
branches:
  only:
  - master
notifications:
  email: false
before_script:
- bash ./prepare.sh
script:
- cd SwipesForScience; npm run build
after_success:
- cd ..; bash ./deploy.sh
env:
  global:
  - GH_USER: pshivraj
  - GH_REPO: megaptera
